#ifndef __SAKURAKVMD_USBHID_GADGET_DEFS_H__
#define __SAKURAKVMD_USBHID_GADGET_DEFS_H__

#define NUM_MODIFIER_BITS 4
#define KEY_REPORT_LENGTH 8
#define PTR_REPORT_LENGTH 6
#define HID_REPORT_RETRY_MAX 10
#define HID_REPORT_RETRY_INTERVAL_US 10000

#endif
